import { DesignReport, DesignToken, RepoMap } from "../core/types.js";

const COLOR_VALUE = /^(#[0-9a-f]{3,8}|rgba?\(|hsla?\(|oklch\()/i;

export function categorizeTokens(tokens: DesignToken[]): Record<string, DesignToken[]> {
  const cats: Record<string, DesignToken[]> = { colors: [], typography: [], spacing: [], radius: [], shadows: [], other: [] };
  for (const t of tokens) {
    const n = t.name.toLowerCase();
    if (n.includes("color") || COLOR_VALUE.test(t.value)) cats.colors.push(t);
    else if (n.includes("font") || n.includes("text") || n.includes("letter") || n.includes("line-height")) cats.typography.push(t);
    else if (n.includes("spac") || n.includes("gap") || n.includes("margin") || n.includes("padding") || n.includes("size")) cats.spacing.push(t);
    else if (n.includes("radius") || n.includes("rounded")) cats.radius.push(t);
    else if (n.includes("shadow")) cats.shadows.push(t);
    else cats.other.push(t);
  }
  return cats;
}

/** v0.2: generate .ria/DESIGN.md from detected tokens + components. */
export function generateDesignMd(report: DesignReport, map: RepoMap): string {
  const cats = categorizeTokens(report.tokens);
  const projectName = map.root.split(/[\\/]/).pop();
  const out: string[] = [];
  out.push(`# DESIGN.md — ${projectName}`, ``);
  out.push(`> Generated by AI RIA (\`ria design\`). The design contract for humans and AI agents.`);
  out.push(`> Agents: use these tokens. Do not hardcode colors, spacing, or radii.`, ``);

  out.push(`## Sources`, ``);
  out.push(`- Hand-written design doc: ${report.hasDesignDoc ? `\`${report.designDocPath}\`` : "none"}`);
  out.push(`- Tailwind config: ${report.hasTailwindConfig ? "yes" : "no"}`);
  out.push(`- Token sources: ${[...new Set(report.tokens.map((t) => t.source))].join(", ") || "none detected"}`, ``);

  const section = (title: string, tokens: DesignToken[], hint: string) => {
    out.push(`## ${title}`, ``);
    if (!tokens.length) {
      out.push(`_None detected._ ${hint}`, ``);
      return;
    }
    out.push(`| Token | Value |`, `|---|---|`);
    for (const t of tokens) out.push(`| \`${t.name}\` | \`${t.value}\` |`);
    out.push(``);
  };

  section("Colors", cats.colors, "Define `--color-*` custom properties.");
  section("Typography", cats.typography, "Define `--font-*` / `--text-*` custom properties.");
  section("Spacing", cats.spacing, "Define a `--spacing-*` scale.");
  section("Border Radius", cats.radius, "Define `--radius-*` custom properties.");
  if (cats.shadows.length) section("Shadows", cats.shadows, "");
  if (cats.other.length) section("Other Tokens", cats.other, "");

  out.push(`## Components`, ``);
  if (map.components.length) {
    out.push(`Reuse these before creating new ones:`, ``);
    for (const c of map.components.slice(0, 40)) out.push(`- \`${c}\``);
    if (map.components.length > 40) out.push(`- … +${map.components.length - 40} more`);
  } else {
    out.push(`_No component files detected._`);
  }
  out.push(``);

  out.push(`## Layout Patterns`, ``);
  const patterns: string[] = [];
  if (report.hasTailwindConfig) patterns.push("Tailwind utility classes — extend the config, don't inline arbitrary values");
  if (map.styles.some((s) => s.includes("global"))) patterns.push("Global stylesheet present — shared tokens belong there");
  if (map.framework === "Next.js" || map.framework === "React") patterns.push(`${map.framework} component composition — style at the component level`);
  if (!patterns.length) patterns.push("No specific layout system detected.");
  for (const p of patterns) out.push(`- ${p}`);
  out.push(``);

  out.push(`## Rules for Agents`, ``);
  out.push(`1. Use tokens above — never hardcode hex colors or pixel values that have a token.`);
  out.push(`2. Reuse existing components before writing new ones.`);
  out.push(`3. If a needed token is missing, add it to the token source first, then use it.`);
  out.push(`4. Run \`ria skill ui-review\` after UI changes.`);
  return out.join("\n");
}
