import { promises as fs } from "node:fs";
import path from "node:path";
import { FigmaTokens, RepoMap, DesignReport } from "../core/types.js";

export interface UiFixSuggestion {
  file: string;
  line: number;
  before: string;
  after: string;
  reason: string;
}

const HEX_LITERAL = /#[0-9a-fA-F]{3,8}\b/g;

/** Tailwind radius scale (px) for radius suggestions. */
const TAILWIND_RADIUS: Record<string, number> = {
  "rounded-sm": 2, "rounded": 4, "rounded-md": 6, "rounded-lg": 8,
  "rounded-xl": 12, "rounded-2xl": 16, "rounded-3xl": 24,
};

function closestTailwindRadius(px: number): string {
  let best = "rounded-md";
  let bestDiff = Infinity;
  for (const [cls, value] of Object.entries(TAILWIND_RADIUS)) {
    const diff = Math.abs(value - px);
    if (diff < bestDiff) { bestDiff = diff; best = cls; }
  }
  return best;
}

/**
 * v0.4: generate UI patch suggestions. Never rewrites files —
 * output is a preview patch (.ria/ui-fix.patch) + report.
 */
export async function buildUiFixSuggestions(
  map: RepoMap,
  design: DesignReport,
  figma: FigmaTokens | null,
): Promise<UiFixSuggestion[]> {
  const suggestions: UiFixSuggestion[] = [];
  const tokenByValue = new Map(design.tokens.map((t) => [t.value.toLowerCase(), t.name]));

  const targetRadiusPx = figma?.radii.length
    ? parseInt(figma.radii[0].value, 10)
    : null;
  const targetRadiusClass = targetRadiusPx ? closestTailwindRadius(targetRadiusPx) : null;

  const uiFiles = [...new Set([...map.components, ...map.styles])];

  for (const file of uiFiles) {
    let content: string;
    try {
      content = await fs.readFile(path.join(map.root, file), "utf8");
    } catch {
      continue;
    }
    content.split("\n").forEach((line, i) => {
      // 1) Hardcoded hex that matches a known token → use the token
      for (const hex of line.match(HEX_LITERAL) ?? []) {
        const token = tokenByValue.get(hex.toLowerCase());
        const isTokenDefinition = /--[a-z0-9-]+\s*:/i.test(line);
        if (token && !isTokenDefinition) {
          suggestions.push({
            file, line: i + 1,
            before: line.trim(),
            after: line.trim().replace(hex, `var(${token})`),
            reason: `Hardcoded ${hex} duplicates token ${token}`,
          });
        }
      }
      // 2) Tailwind radius drift vs Figma
      if (targetRadiusClass) {
        const m = line.match(/\brounded(?:-(?:sm|md|lg|xl|2xl|3xl))?\b/);
        if (m && m[0] !== targetRadiusClass && TAILWIND_RADIUS[m[0]] !== undefined) {
          suggestions.push({
            file, line: i + 1,
            before: line.trim(),
            after: line.trim().replace(m[0], targetRadiusClass),
            reason: `Figma radius is ${targetRadiusPx}px → ${targetRadiusClass}, code uses ${m[0]} (${TAILWIND_RADIUS[m[0]]}px)`,
          });
        }
      }
    });
  }
  return suggestions;
}

/** Render .ria/ui-fix.patch (preview-only diff blocks). */
export function suggestionsToPatch(suggestions: UiFixSuggestion[]): string {
  const byFile = new Map<string, UiFixSuggestion[]>();
  for (const s of suggestions) {
    byFile.set(s.file, [...(byFile.get(s.file) ?? []), s]);
  }
  const out: string[] = [];
  for (const [file, items] of byFile) {
    out.push(`--- a/${file}`);
    out.push(`+++ b/${file}`);
    for (const s of items) {
      out.push(`@@ line ${s.line} @@`);
      out.push(`- ${s.before}`);
      out.push(`+ ${s.after}`);
    }
    out.push(``);
  }
  return out.join("\n") || "# No suggestions — UI is consistent.\n";
}

/** Render .ria/UI_FIX_REPORT.md */
export function suggestionsToReport(suggestions: UiFixSuggestion[]): string {
  const out: string[] = [];
  out.push(`# UI Fix Report (preview)`, ``);
  out.push(`> Generated by \`ria ui-fix --preview\`. No files were modified.`, ``);
  if (!suggestions.length) {
    out.push(`✅ No inconsistencies found.`);
    return out.join("\n");
  }
  out.push(`${suggestions.length} suggestion(s). Apply manually or via your agent after review.`, ``);
  for (const s of suggestions) {
    out.push(`## \`${s.file}:${s.line}\``, ``);
    out.push(`**Why:** ${s.reason}`, ``);
    out.push("```diff");
    out.push(`- ${s.before}`);
    out.push(`+ ${s.after}`);
    out.push("```", ``);
  }
  return out.join("\n");
}
