import { ContextPack, DesignReport, RepoMap, RiaSummary, RiaSummarySchema, SecurityReport } from "../core/types.js";
import { compressRepoMap } from "../compression/compressor.js";

const name = (map: RepoMap) => map.root.split(/[\\/]/).pop() ?? "project";

/** .ria/ARCHITECTURE.md — how the project is built. */
export function generateArchitectureMd(map: RepoMap): string {
  const out: string[] = [];
  out.push(`# Architecture — ${name(map)}`, ``);
  out.push(`> Generated by AI RIA (\`ria analyze\`). Agent-readable repository knowledge.`, ``);
  out.push(`## Stack`, ``);
  out.push(`- Framework: **${map.framework}**`);
  out.push(`- Language: ${map.conventions.usesTypeScript ? "TypeScript" : "JavaScript"}`);
  out.push(`- Package manager: ${map.conventions.packageManager}`);
  out.push(`- Files: ${map.fileCount} · Lines: ${map.totalLines}`, ``);
  out.push(`## Layout`, ``);
  for (const [dir, count] of Object.entries(map.topLevelDirs).sort((a, b) => b[1] - a[1])) {
    out.push(`- \`${dir}\` — ${count} files`);
  }
  if (map.entryPoints.length) {
    out.push(``, `## Entry Points`, ``);
    for (const e of map.entryPoints) out.push(`- \`${e}\``);
  }
  if (map.configFiles.length) {
    out.push(``, `## Configuration`, ``);
    for (const c of map.configFiles) out.push(`- \`${c}\``);
  }
  out.push(``, `## Dependencies`, ``);
  out.push(`- Runtime: ${map.dependencies.join(", ") || "none"}`);
  out.push(`- Dev: ${map.devDependencies.join(", ") || "none"}`);
  return out.join("\n");
}

/** .ria/FEATURES.md — what the project does, inferred from routes/components/scripts. */
export function generateFeaturesMd(map: RepoMap): string {
  const out: string[] = [];
  out.push(`# Features — ${name(map)}`, ``);
  if (map.routes.length) {
    out.push(`## Routes / Pages`, ``);
    for (const r of map.routes) out.push(`- \`${r || "/"}\``);
    out.push(``);
  }
  if (map.components.length) {
    out.push(`## Components`, ``);
    for (const c of map.components.slice(0, 40)) out.push(`- \`${c}\``);
    if (map.components.length > 40) out.push(`- … +${map.components.length - 40} more`);
    out.push(``);
  }
  if (Object.keys(map.scripts).length) {
    out.push(`## Available Commands`, ``);
    for (const [k, v] of Object.entries(map.scripts)) out.push(`- \`${k}\` → \`${v}\``);
    out.push(``);
  }
  if (map.styles.length) {
    out.push(`## Styling`, ``);
    for (const s of map.styles.slice(0, 20)) out.push(`- \`${s}\``);
  }
  if (!map.routes.length && !map.components.length && !Object.keys(map.scripts).length) {
    out.push(`No routes, components, or scripts detected. This may be a library or plain content project.`);
  }
  return out.join("\n");
}

/** .ria/AGENTS.md — operating instructions for AI agents working on this repo. */
export function generateAgentsMd(map: RepoMap): string {
  const pm = map.conventions.packageManager === "unknown" ? "npm" : map.conventions.packageManager;
  const out: string[] = [];
  out.push(`# Agent Instructions — ${name(map)}`, ``);
  out.push(`Rules for AI agents working in this repository. Read \`.ria/AGENT_CONTEXT.md\` first — it is the token-cheap summary of everything.`, ``);
  out.push(`## Conventions to Respect`, ``);
  out.push(`- Framework: ${map.framework}. Follow its idioms.`);
  out.push(`- ${map.conventions.usesTypeScript ? "TypeScript project — keep strict typing, no `any`." : "JavaScript project."}`);
  if (map.conventions.hasSrcLayout) out.push(`- Source code lives in \`src/\`. Do not create source files outside it.`);
  if (map.conventions.hasTests) out.push(`- Tests exist — run them after changes and add tests for new code.`);
  if (map.conventions.hasDesignDoc) out.push(`- A design doc exists — generated UI must follow \`.ria/DESIGN.md\` tokens.`);
  out.push(`- Use \`${pm}\` for package operations.`, ``);
  out.push(`## Commands`, ``);
  const scripts = Object.keys(map.scripts);
  if (scripts.length) {
    for (const s of ["dev", "build", "test", "lint"].filter((s) => scripts.includes(s))) {
      out.push(`- \`${pm} ${s === "test" ? "test" : `run ${s}`}\``);
    }
  } else {
    out.push(`- No package scripts detected.`);
  }
  out.push(``, `## Safety`, ``);
  out.push(`- Never commit secrets. Run \`ria security\` before finalizing changes.`);
  out.push(`- Do not edit files in \`.ria/\` by hand — they are generated.`);
  return out.join("\n");
}

/** .ria/AGENT_CONTEXT.md — single compressed context entry point for agents. */
export function generateAgentContextMd(map: RepoMap): string {
  const ctx = compressRepoMap(map);
  const out: string[] = [];
  out.push(`# Agent Context — ${name(map)}`, ``);
  out.push(`Compressed repository context (~${ctx.tokenEstimate} tokens vs ~${ctx.originalTokenEstimate} raw, ratio ${ctx.compressionRatio}).`, ``);
  out.push("```");
  out.push(ctx.summary);
  out.push("```", ``);
  out.push(`## Where to Look Next`, ``);
  out.push(`| Need | File |`);
  out.push(`|---|---|`);
  out.push(`| Architecture details | \`.ria/ARCHITECTURE.md\` |`);
  out.push(`| Feature inventory | \`.ria/FEATURES.md\` |`);
  out.push(`| Working rules | \`.ria/AGENTS.md\` |`);
  out.push(`| Full file-level context | \`.ria/context-pack.md\` (run \`ria compress\`) |`);
  out.push(`| Design system | \`.ria/DESIGN.md\` (run \`ria design\`) |`);
  out.push(`| Security posture | \`.ria/SECURITY_REPORT.md\` (run \`ria security\`) |`);
  return out.join("\n");
}

/** .ria/summary.json — machine-readable rollup for agents and CI. */
export function buildSummary(
  map: RepoMap,
  design: DesignReport,
  security: SecurityReport,
  pack: ContextPack,
  generatedFiles: string[],
): RiaSummary {
  return RiaSummarySchema.parse({
    tool: "ai-ria",
    version: "0.2.0",
    generatedAt: new Date().toISOString(),
    root: map.root,
    framework: map.framework,
    packageManager: map.conventions.packageManager,
    usesTypeScript: map.conventions.usesTypeScript,
    counts: {
      files: map.fileCount,
      lines: map.totalLines,
      routes: map.routes.length,
      components: map.components.length,
      styles: map.styles.length,
      designTokens: design.tokenCount,
      securityFindings: security.findings.length,
      criticalOrHigh: security.findings.filter((f) => f.severity === "critical" || f.severity === "high").length,
    },
    compression: {
      packTokens: pack.totalTokens,
      rawTokens: pack.originalTokenEstimate,
      ratio: pack.compressionRatio,
    },
    generatedFiles,
  });
}
